# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Štatistický slovník online
email: statisticky.slovnik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Štatistický slovník online bol vyvinutý v dôsledku frustrácie autora z nedostatku slovenských zdrojov na internete, ktoré by obsahovali komplexný zoznam slovenských štatistických výrazov, ich výkladu a anglických ekvivalentov. Jedná sa o voľnočasový projekt 1 človeka, preto prosím o zľutovanie ak nájdeš nejaké chyby. Ako autor však ocením, ak mi o nich dáš vedieť!
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  kolace

# Build settings
markdown: kramdown
